# Generated by Django 4.2 on 2025-11-09 01:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0003_bookedslot_availabilityslot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(help_text='Date of the training session')),
                ('start_time', models.TimeField(help_text='Session start time')),
                ('end_time', models.TimeField(help_text='Session end time')),
                ('duration_minutes', models.IntegerField(help_text='Session duration in minutes', validators=[django.core.validators.MinValueValidator(15)])),
                ('location_address', models.CharField(help_text='Where the session will take place', max_length=255)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text="Trainer's hourly rate at time of booking", max_digits=6)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for this session', max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending - Awaiting trainer confirmation'), ('confirmed', 'Confirmed - Session scheduled'), ('cancelled_by_client', 'Cancelled by Client'), ('cancelled_by_trainer', 'Cancelled by Trainer'), ('completed', 'Completed'), ('no_show', 'No Show')], default='pending', max_length=30)),
                ('client_notes', models.TextField(blank=True, help_text='Special requests or focus areas from client')),
                ('trainer_notes', models.TextField(blank=True, help_text='Private notes for trainer')),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_made', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_received', to='trainers.trainerprofile')),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'ordering': ['-session_date', '-start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['trainer', 'session_date', 'status'], name='bookings_bo_trainer_8c93af_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client', 'session_date', 'status'], name='bookings_bo_client__75582a_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'session_date'], name='bookings_bo_status_9d7223_idx'),
        ),
    ]
