# Generated by Django 4.2 on 2025-11-14 01:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainers', '0004_trainerprofile_trainers_tr_locatio_36a0a6_idx'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1-5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Written review (optional)')),
                ('is_verified', models.BooleanField(default=True, help_text='Verified purchase (auto-set from booking)')),
                ('is_visible', models.BooleanField(default=True, help_text='Admin can hide inappropriate reviews')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(help_text='The booking being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trainers.trainerprofile')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['trainer', '-created_at'], name='bookings_re_trainer_3baed5_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['client', '-created_at'], name='bookings_re_client__f281af_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='bookings_re_rating_a9b587_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('booking',), name='one_review_per_booking'),
        ),
    ]
