# Generated by Django 4.2 on 2025-11-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_review_review_bookings_re_trainer_3baed5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid - Payment not initiated'), ('pending', 'Pending - Payment in progress'), ('paid', 'Paid - Payment successful'), ('failed', 'Failed - Payment unsuccessful'), ('refunded', 'Refunded - Payment refunded')], default='unpaid', help_text='Payment status for this booking', max_length=20),
        ),
    ]
