# Generated by Django 4.2 on 2025-11-07 21:52

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon class', max_length=50)),
            ],
            options={
                'verbose_name': 'specialization',
                'verbose_name_plural': 'specializations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Tell clients about your training philosophy', max_length=500)),
                ('years_experience', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('address', models.CharField(blank=True, max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Geocoded coordinates from address', null=True, srid=4326)),
                ('service_radius_miles', models.IntegerField(default=10, help_text='How far trainer will travel to clients')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('verified', models.BooleanField(default=False, help_text='Background check completed')),
                ('verification_expires', models.DateField(blank=True, help_text='Verification expires 12 months after completion', null=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.IntegerField(default=0)),
                ('profile_complete', models.BooleanField(default=False, help_text='Profile has all required fields')),
                ('published', models.BooleanField(default=False, help_text='Profile visible in search')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specializations', models.ManyToManyField(blank=True, help_text='Fitness specializations (Yoga, HIIT, etc.)', related_name='trainers', to='trainers.specialization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile_new', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'trainer profile',
                'verbose_name_plural': 'trainer profiles',
            },
        ),
        migrations.CreateModel(
            name='TrainerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='trainers/photos/')),
                ('photo_type', models.CharField(choices=[('profile', 'Profile Photo'), ('gym', 'Training Space'), ('credentials', 'Certifications'), ('action', 'Training Sessions')], default='gym', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='trainers.trainerprofile')),
            ],
            options={
                'verbose_name': 'trainer photo',
                'verbose_name_plural': 'trainer photos',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainerCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'NASM Certified Personal Trainer'", max_length=100)),
                ('issuing_organization', models.CharField(max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Leave blank if no expiry', null=True)),
                ('credential_id', models.CharField(blank=True, max_length=100)),
                ('document', models.FileField(blank=True, help_text='Upload certification document (PDF or image)', upload_to='trainers/certifications/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='trainers.trainerprofile')),
            ],
            options={
                'verbose_name': 'trainer certification',
                'verbose_name_plural': 'trainer certifications',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.AddIndex(
            model_name='trainerprofile',
            index=models.Index(fields=['verified', 'published'], name='trainers_tr_verifie_26dece_idx'),
        ),
        migrations.AddIndex(
            model_name='trainerprofile',
            index=models.Index(fields=['average_rating'], name='trainers_tr_average_f22bf3_idx'),
        ),
    ]
