# Generated by Django 4.2 on 2025-11-07 21:52

from django.db import migrations


def populate_specializations(apps, schema_editor):
    """Populate default fitness specializations"""
    Specialization = apps.get_model('trainers', 'Specialization')

    # Import slugify for manual slug generation
    from django.utils.text import slugify

    specializations = [
        {'name': 'Strength Training', 'icon': '💪', 'description': 'Build muscle and increase strength'},
        {'name': 'Yoga', 'icon': '🧘', 'description': 'Flexibility, balance, and mindfulness'},
        {'name': 'HIIT', 'icon': '🔥', 'description': 'High-intensity interval training'},
        {'name': 'Cardio', 'icon': '🏃', 'description': 'Cardiovascular endurance training'},
        {'name': 'Pilates', 'icon': '🤸', 'description': 'Core strength and flexibility'},
        {'name': 'CrossFit', 'icon': '🏋️', 'description': 'Functional fitness and conditioning'},
        {'name': 'Boxing', 'icon': '🥊', 'description': 'Boxing technique and fitness'},
        {'name': 'Cycling', 'icon': '🚴', 'description': 'Indoor and outdoor cycling'},
        {'name': 'Running', 'icon': '🏃‍♀️', 'description': 'Running technique and endurance'},
        {'name': 'Nutrition', 'icon': '🥗', 'description': 'Diet and nutrition coaching'},
        {'name': 'Weight Loss', 'icon': '⚖️', 'description': 'Weight management and fat loss'},
        {'name': 'Sports Performance', 'icon': '⚽', 'description': 'Sport-specific training'},
        {'name': 'Rehabilitation', 'icon': '🩹', 'description': 'Injury recovery and prevention'},
        {'name': 'Senior Fitness', 'icon': '👴', 'description': 'Fitness for older adults'},
        {'name': 'Prenatal/Postnatal', 'icon': '🤰', 'description': 'Training for pregnancy'},
    ]

    for spec_data in specializations:
        Specialization.objects.get_or_create(
            name=spec_data['name'],
            defaults={
                'slug': slugify(spec_data['name']),  # Manually generate slug
                'icon': spec_data['icon'],
                'description': spec_data['description']
            }
        )


def reverse_populate(apps, schema_editor):
    """Remove seeded specializations"""
    Specialization = apps.get_model('trainers', 'Specialization')
    Specialization.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_specializations, reverse_populate),
    ]
