# Generated by Django 4.2 on 2025-11-08 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainers', '0002_populate_specializations'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(help_text='Booking start date and time')),
                ('end_datetime', models.DateTimeField(help_text='Booking end date and time')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Client notes or special requests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_training_slots', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_slots', to='trainers.trainerprofile')),
            ],
            options={
                'verbose_name': 'booked slot',
                'verbose_name_plural': 'booked slots',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='0=Monday, 6=Sunday')),
                ('start_time', models.TimeField(help_text='Start time (e.g., 09:00)')),
                ('end_time', models.TimeField(help_text='End time (e.g., 17:00)')),
                ('is_available', models.BooleanField(default=True, help_text='Toggle to temporarily disable without deleting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='trainers.trainerprofile')),
            ],
            options={
                'verbose_name': 'availability slot',
                'verbose_name_plural': 'availability slots',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='bookedslot',
            index=models.Index(fields=['trainer', 'start_datetime', 'status'], name='trainers_bo_trainer_b9711f_idx'),
        ),
        migrations.AddIndex(
            model_name='bookedslot',
            index=models.Index(fields=['client', 'start_datetime'], name='trainers_bo_client__63c8f7_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['trainer', 'day_of_week', 'is_available'], name='trainers_av_trainer_abdc3e_idx'),
        ),
    ]
