# Generated by Django 4.2 on 2025-11-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_bookedslot_availabilityslot_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trainerprofile',
            index=models.Index(fields=['location'], name='trainers_tr_locatio_36a0a6_idx'),
        ),
    ]
