# Generated by Django 4.2 on 2025-11-16 02:45

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_booking_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainers', '0004_trainerprofile_trainers_tr_locatio_36a0a6_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(help_text='Stripe PaymentIntent ID', max_length=255, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, help_text='Stripe Charge ID (after payment succeeds)', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in dollars', max_digits=8)),
                ('currency', models.CharField(default='usd', help_text='Currency code (USD, EUR, etc.)', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending - Payment initiated'), ('processing', 'Processing - Awaiting confirmation'), ('succeeded', 'Succeeded - Payment completed'), ('failed', 'Failed - Payment unsuccessful'), ('canceled', 'Canceled - Payment canceled'), ('refunded', 'Refunded - Payment refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=30)),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Platform fee percentage (default 15%)', max_digits=4)),
                ('platform_fee_amount', models.DecimalField(decimal_places=2, help_text='Calculated platform fee in dollars', max_digits=8)),
                ('trainer_payout_amount', models.DecimalField(decimal_places=2, help_text='Amount trainer receives after platform fee', max_digits=8)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount refunded', max_digits=8)),
                ('refund_reason', models.TextField(blank=True, help_text='Reason for refund')),
                ('refunded_at', models.DateTimeField(blank=True, help_text='When the refund was processed', null=True)),
                ('payment_method_type', models.CharField(blank=True, help_text='Payment method (card, etc.)', max_length=50)),
                ('card_brand', models.CharField(blank=True, help_text='Card brand (Visa, Mastercard, etc.)', max_length=20)),
                ('card_last4', models.CharField(blank=True, help_text='Last 4 digits of card', max_length=4)),
                ('receipt_url', models.URLField(blank=True, help_text='Stripe receipt URL')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional payment metadata')),
                ('failure_code', models.CharField(blank=True, help_text='Stripe failure code if payment failed', max_length=100)),
                ('failure_message', models.TextField(blank=True, help_text='Stripe failure message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(help_text='The booking this payment is for', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking')),
                ('client', models.ForeignKey(help_text='Client who made the payment', on_delete=django.db.models.deletion.PROTECT, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(help_text='Trainer receiving the payment', on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to='trainers.trainerprofile')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['client', '-created_at'], name='payments_pa_client__ef8bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['trainer', '-created_at'], name='payments_pa_trainer_1c8d89_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='payments_pa_status_21ed42_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_payment_intent_id'], name='payments_pa_stripe__6fe52c_idx'),
        ),
    ]
