# Generated by Django 4.2 on 2025-11-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_bookedslot_availabilityslot_and_more'),
        ('users', '0002_trainerprofile_clientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='preferred_specializations',
            field=models.ManyToManyField(blank=True, help_text="Client's preferred training specializations", related_name='interested_clients', to='trainers.specialization'),
        ),
    ]
