# Generated by Django 4.2 on 2025-11-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_clientprofile_preferred_specializations'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='current_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current weight in kilograms', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='dietary_restrictions',
            field=models.TextField(blank=True, help_text='Dietary restrictions or preferences'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='fitness_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('athlete', 'Athlete')], default='beginner', help_text='Current fitness level', max_length=20),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='health_conditions',
            field=models.TextField(blank=True, help_text='Any health conditions or injuries trainers should know about'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='height_cm',
            field=models.IntegerField(blank=True, help_text='Height in centimeters', null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='medications',
            field=models.TextField(blank=True, help_text='Current medications (optional)'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='preferred_session_duration',
            field=models.IntegerField(blank=True, help_text='Preferred session duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='preferred_training_style',
            field=models.CharField(blank=True, help_text="e.g., 'High intensity', 'Low impact', 'Bodyweight only'", max_length=100),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='preferred_workout_days',
            field=models.JSONField(blank=True, default=list, help_text="Preferred days of week for workouts (e.g., ['monday', 'wednesday', 'friday'])"),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='preferred_workout_times',
            field=models.JSONField(blank=True, default=list, help_text="Preferred times of day (e.g., ['morning', 'evening'])"),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='primary_goal',
            field=models.CharField(blank=True, choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('endurance', 'Build Endurance'), ('strength', 'Build Strength'), ('flexibility', 'Improve Flexibility'), ('general_fitness', 'General Fitness'), ('sports_performance', 'Sports Performance'), ('rehabilitation', 'Rehabilitation'), ('stress_relief', 'Stress Relief')], help_text='Primary fitness goal', max_length=30),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='profile_complete',
            field=models.BooleanField(default=False, help_text='True if client has completed their fitness profile'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='secondary_goals',
            field=models.JSONField(blank=True, default=list, help_text='Additional fitness goals (stored as list)'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='sessions_per_week',
            field=models.IntegerField(blank=True, help_text='Desired number of training sessions per week', null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='target_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target weight in kilograms', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell trainers about yourself', max_length=500),
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['user'], name='users_clien_user_id_3161ed_idx'),
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['fitness_level'], name='users_clien_fitness_4241ba_idx'),
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['primary_goal'], name='users_clien_primary_07ab8e_idx'),
        ),
    ]
