# Generated by Django 4.2 on 2025-11-14 05:40

from django.db import migrations, models


def convert_metric_to_imperial(apps, schema_editor):
    """Convert existing metric values to imperial"""
    ClientProfile = apps.get_model('users', 'ClientProfile')

    for profile in ClientProfile.objects.all():
        # Convert height: cm to inches (1 cm = 0.393701 inches)
        if profile.height_cm:
            profile.height_inches = round(float(profile.height_cm) * 0.393701, 1)

        # Convert current weight: kg to lbs (1 kg = 2.20462 lbs)
        if profile.current_weight_kg:
            profile.current_weight_lbs = round(float(profile.current_weight_kg) * 2.20462, 1)

        # Convert target weight: kg to lbs (1 kg = 2.20462 lbs)
        if profile.target_weight_kg:
            profile.target_weight_lbs = round(float(profile.target_weight_kg) * 2.20462, 1)

        profile.save()


def convert_imperial_to_metric(apps, schema_editor):
    """Reverse conversion for rollback"""
    ClientProfile = apps.get_model('users', 'ClientProfile')

    for profile in ClientProfile.objects.all():
        # Convert height: inches to cm (1 inch = 2.54 cm)
        if profile.height_inches:
            profile.height_cm = round(float(profile.height_inches) * 2.54)

        # Convert current weight: lbs to kg (1 lb = 0.453592 kg)
        if profile.current_weight_lbs:
            profile.current_weight_kg = round(float(profile.current_weight_lbs) * 0.453592, 2)

        # Convert target weight: lbs to kg (1 lb = 0.453592 kg)
        if profile.target_weight_lbs:
            profile.target_weight_kg = round(float(profile.target_weight_lbs) * 0.453592, 2)

        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_clientprofile_current_weight_kg_and_more'),
    ]

    operations = [
        # Step 1: Add new imperial fields
        migrations.AddField(
            model_name='clientprofile',
            name='current_weight_lbs',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Current weight in pounds', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='height_inches',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Height in inches', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='target_weight_lbs',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Target weight in pounds', max_digits=5, null=True),
        ),

        # Step 2: Convert existing data
        migrations.RunPython(convert_metric_to_imperial, convert_imperial_to_metric),

        # Step 3: Remove old metric fields
        migrations.RemoveField(
            model_name='clientprofile',
            name='current_weight_kg',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='height_cm',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='target_weight_kg',
        ),
    ]
